[project]
name = "benris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"beautifulsoup4>=4.14.2",
	"duckduckgo-search>=8.1.1",
	"groq>=0.37.1",
	"phidata>=2.7.10",
	"pyaudio>=0.2.14",
	"pyqt5>=5.15.11",
	"pyttsx3>=2.99",
	"requests>=2.32.5",
	"speechrecognition>=3.14.3",
	"wikipedia>=1.4.0",
]
